Issue #1629
fieldenms/tg pull request #1630
Opened 2021-01-14 15:28 UTC by oleh-maikovych

resolve #1629

2021-01-22 05:12 UTC, elvin-fms approved these changes

2021-01-27 23:14 UTC, 01es requested changes

2021-01-28 10:57 UTC, oleh-maikovych commented on platform-dao/src/test/java/ua/com/fielden/platform/validators/OverlappingDateOnlyTest.java
> +    public void test_overlapping_for_new_with_intersect_at_the_beginning() {
@01es, I have renamed unit test, please check and advice.

2021-01-28 11:00 UTC, oleh-maikovych commented on platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgDateTestEntity.java
> +public class TgDateTestEntity extends AbstractEntity<String> {
@01es, thanks for advice. I have successfully applied `tgprop-from-and-to` template that added validators for inversion to from/to properties.

2021-01-29 08:26 UTC, 01es approved these changes
It would be nice to also have tests for mixed periods with @DateOnly for the start only, and with @DateOnly for the end only. But, let's consider this as non-critical due to unlikely scenario of having date periods for "mixed" start and end in practice.

2021-01-29 08:26 UTC, merged